version: '3'
services:
  backend:
    container_name: go_backend
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./src/backend:/go/src/app
  frontend:
    container_name: next_frontend
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    command: "npm run dev"
    tty: true
    volumes:
      - ./src/frontend:/app
    ports:
      - "3000:3000"
