version: '3'
services:
  backend:
    container_name: go_backend
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    # command: [ "go run main.go" ]
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./src/backend:/app
  frontend:
    container_name: next_frontend
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    command: "npm run dev"
    tty: true
    volumes:
      - ./src/frontend:/app
    ports:
      - "3000:3000"
  # swagger
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./api/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml

  swagger-api:
    image: stoplight/prism:3
    container_name: "swagger-api"
    ports:
      - "8003:4010"
    command: mock -h 0.0.0.0 /openapi.yaml
    volumes:
      - ./api/openapi.yaml:/openapi.yaml
